GET http://localhost:3000/subscribers
###

GET http://localhost:3000/subscribers/629133915a05078e2fae1c6d
###


DELETE http://localhost:3000/subscribers/629133915a05078e2fae1c6d
###

POST http://localhost:3000/subscribers
Content-Type: application/json 

{
    "name": "Akshay Kumar",
    "subscribedTo": "Web dev simplified"
}